version: "3.8"
services:
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root # Définir le mot de passe root pour MySQL
      MYSQL_DATABASE: price_comparator  # Nom de la base de données
      MYSQL_USER: user  # Utilisateur supplémentaire
      MYSQL_PASSWORD: password  # Mot de passe de cet utilisateur
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


  scraper:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./scraper:/app
    command: ["bash", "-c", "pip install scrapy && scrapy crawl amazon"]
    depends_on:
      - database
 
  webapp:
    build: ./webapp
    ports:
      - "5000:5000"
    depends_on:
      - database
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database  # Le service MySQL dans Docker Compose
      MYSQL_ROOT_PASSWORD: root # Le mot de passe root MySQL
    ports:
      - "8080:80"
    depends_on:
      - database